INSERT INTO category (name) VALUES
('Japonesa'),
('Brasileira'),
('Pizza'),
('Hambúrguer'),
('Italiana'),
('Árabe'),
('Chinesa'),
('Mexicana'),
('Lanches'),
('Açaí'),
('Sobremesas'),
('Padaria'),
('Bebidas'),
('Saudável'),
('Vegetariana') ON CONFLICT DO NOTHING;